[WIP] /src/null-safety/understanding-null-safety/index.md
cfug/dart.cn pull request #212
Opened 2020-08-03 08:39 UTC by AlexV525

Resolves #210 .

2020-08-30 14:09 UTC, AlexV525 commented
Yep, it's finally done, and ready to go! 🚀

2020-09-07 14:15 UTC, chenglu commented on src/null-safety/understanding-null-safety/index.md
> +空安全已经成为[老生常谈][billion]。让我们来看下面这个例子：
```suggestion
空安全已经成为 [老生常谈][billion]。让我们来看下面这个例子：
```

2020-09-07 14:15 UTC, chenglu commented on src/null-safety/understanding-null-safety/index.md
> +`null` 值是 `Null` 类的一个实例，而 `Null` 没有 "length" getter。
```suggestion
`null` 值是 `Null` 类的一个实例，而 `Null` 没有 "length" 的 getter 方法。
```
我的理解对不？

2020-09-07 14:16 UTC, chenglu commented on src/null-safety/understanding-null-safety/index.md
> +这篇文档很长。如果您只需要一份如何开始并运行的简短的文档，请从[概览][overview]开始。
```suggestion
这篇文档很长。如果您只需要一份如何开始并运行的简短的文档，请从 [概览][overview] 开始。
```

2020-09-07 14:52 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +`null` 值是 `Null` 类的一个实例，而 `Null` 没有 "length" getter。
我一直不太确定 getter 要怎么翻译，因为平时说到 getter 的时候大家都知道是啥内容…

2020-09-08 07:31 UTC, chenglu commented on src/null-safety/understanding-null-safety/index.md
> +（在这个情况下，您的有向图是一种[偏序集合 (lattice)][lattice]）
```suggestion
（在这个情况下，您的有向图是一种 [偏序集合 (lattice)][lattice]）
```

2020-09-18 06:14 UTC, chenglu approved these changes
Looks good.

2020-09-18 06:30 UTC, AlexV525 commented
> Looks good.

憋着急，才25%润稿呢 🤣

2020-09-23 06:18 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +您没有办法声明一个**必需的**可空类型参数。
这里的解读有一些疑惑，尚不清楚合理的解读方式

2020-09-24 14:13 UTC, lidemin commented on src/null-safety/understanding-null-safety/index.md
> +您可以将未初始化的变量声明为类型参数的类型。
```suggestion
这意味着在类的主体中，您拥有了可以将类型参数当作可空的灵活性。
请注意，这一次我们没有构造函数，但是这也是可以的。
字段将会被隐式初始化为 `null`。
您可以将未初始化的变量声明为类型参数的类型。
```

2020-09-24 14:13 UTC, lidemin commented on src/null-safety/understanding-null-safety/index.md
> +所以在我们调用 `<=` 前，流程分析将它们提升成了非空类型。
```suggestion
但您也受到了可空性的限制，除非您先处理了可空状态，否则您无法调用变量的任何方法。
在此处的例子中，我们将字段拷贝至局部变量，并且检查了它们是否为 `null`，
所以在我们调用 `<=` 前，控制流分析将它们提升成了非空类型。
```

2020-09-24 14:13 UTC, lidemin commented on src/null-safety/understanding-null-safety/index.md
> +所以在我们调用 `<=` 前，流程分析将它们提升成了非空类型。
https://dart.dev/null-safety/understanding-null-safety#flow-analysis

https://en.wikipedia.org/wiki/Control_flow_analysis

2020-09-24 14:13 UTC, lidemin commented on src/null-safety/understanding-null-safety/index.md
> +您没有办法声明一个**必需的**可空类型参数。
```suggestion
请注意，可空的类型约束并不会阻止用户使用非空类型来实例化这个类。
一个可空的类型约束意味着类型参数**可以**为空，而不是**必须**为空。
（实际上，如果您没有写上 `extends` 语句，类型参数的默认类型约束的是可空的 `Object?`。）
您没有办法声明一个**必需的**可空类型参数。
```

2020-09-24 14:13 UTC, lidemin commented on src/null-safety/understanding-null-safety/index.md
> +如果您希望类型参数的使用是可靠的且可空的，您可以在类中使用 `T?`。
```suggestion
如果您希望确保类型参数一定是可空的，您可以在类的主体中使用 `T?`。
```

2020-09-24 14:41 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +您没有办法声明一个**必需的**可空类型参数。
非常感谢！对于该段的最后一句，是否还有更好的解答呢？

2020-09-25 00:36 UTC, lidemin commented on src/null-safety/understanding-null-safety/index.md
> +您没有办法声明一个**必需的**可空类型参数。
> There is no way to *require* a nullable type argument.
> 您没有办法声明一个**必需的**可空类型参数。

是指这一句吗？我觉得最初的翻译挺准确的。

2020-09-25 01:09 UTC, CaiJingLong reviewed
check了所有翻译内容, 感谢你的辛勤工作

2020-09-25 02:28 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +所以在我们调用 `<=` 前，流程分析将它们提升成了非空类型。
关于“流程分析”和“控制流分析”，我也在wiki上补充了相关的知识，而后发现在这里的 flow analysis 好像更强调的是流程，再在其中穿插控制流分析。

2020-09-25 05:22 UTC, AlexV525 commented
@lidemin 总体来说，我想保留相对口语化、能让读者在阅读中不会误解，但某些部分非常有意思的解读。朝着这个方向，有一些句子可能不一定要完全按照原意一字一句的翻译~

2020-09-25 06:25 UTC, lidemin commented
> @lidemin 总体来说，我想保留相对口语化、能让读者在阅读中不会误解，但某些部分非常有意思的解读。朝着这个方向，有一些句子可能不一定要完全按照原意一字一句的翻译~

其实没太看懂这句话 😂

文档的翻译最终应该帮助中文用户可以更容易的理解它，逐字逐句的翻译有时候很容易误导读者。所以有时候我会更倾向直接把意思总结出来。如果意思我理解错了的话，估计我也不会翻译对，所以欢迎讨论。

2020-09-25 06:33 UTC, AlexV525 commented
> @AlexV525 其实没太看懂这句话 😂
> 
> 文档的翻译最终应该帮助中文用户可以更容易的理解它，逐字逐句的翻译有时候很容易误导读者。所以有时候我会更倾向直接把意思总结出来。如果意思我理解错了的话，估计我也不会翻译对，所以欢迎讨论。

啊，大概就是相对通俗易懂，同时包含一些常见的说法，或者轻微地埋个梗之类的~因为实在是太长了

2020-09-30 02:51 UTC, AlexV525 commented
Scheduled to merge the doc at 12/13 Oct if there are no further reviews.

2020-10-06 06:34 UTC, Vadaski requested changes
review 到 200，大部分都是我碎碎叨，供 Alex 参考

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +但当一个 Flutter 应用在用户的手机上崩溃时，他们绝对不会感到开心。
「但当一个 Flutter 应用在用户的手机上崩溃时，他们绝对不会感到开心。」=>「但如果是 Flutter 应用在用户的手机上崩溃了，就会严重影响用户体验」

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +如果一个服务器应用出现了异常，您可以快速对它进行重启，而不被其他人察觉。
「其他人」其实指的就是「用户」

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +因为它可以让开发者在开发时，更多时候是在使用 IDE 编译时，通过类型检查发现错误。
「因为它可以让开发者在开发时，更多时候是在使用 IDE 编译时，通过类型检查发现错误。」
这句感觉拉的有点长，
「因为它能够让开发者在使用 IDE 编译期间，就能通过类型检查机制发现错误。」如何

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +它包含了对静态类型系统的修改、一系列的修改及新的语言特性，
「它包含了对静态类型系统的修改、一系列的修改及新的语言特性」=>「它包含了对静态类型系统以及诸多其他方面的修改，以及新的语言特性」

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +    现有的大多数 Dart 代码都是动态正确的，并且不会抛出空引用错误。
「dynamically correct」 是啥意思，我没太理解。「动态正确」应该怎么理解呢

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +    （不过，请注意第一条原则：您可以选择在运行时将检查放在任何位置。）
「Though, note the first principle: any place where those runtime checks
    happen will be your choice.」结合第一条原则，我理解这句话是在说，什么时候进行检查是完全由你决定的（编译期检查还是运行期检查）

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +    代码的健全性极大程度影响用户对于代码的信心程度。
这里「confidence」我理解是信赖程度，「代码是否健全将很大程度地影响用户的信赖」

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +    一艘**大部分时间**都在漂浮状态的小船，
船当然会飘着拉，「一艘**大部分时间**都在漂浮状态的小船，」=>「一艘经常会**飘忽不定**的小船」

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +    但对于我们无畏的”黑客“编译器而言，仍然十分重要。
「但对于我们无畏的”黑客“编译器而言，仍然十分重要。」=>「这对于我们无畏的”黑客“编译器来说，同样十分重要」
这里应该没有转折关系；）

2020-10-06 06:34 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +`null` 并不糟糕，糟糕的是**在您意想不到的地方出现**，最终引发问题。
「糟糕的是**在您意想不到的地方出现**，最终引发问题。」=>「糟糕的是null**在您意想不到的地方出现**，最终引发问题。」

2020-10-06 13:26 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +空安全已经成为 [老生常谈][billion]。让我们来看下面这个例子：
仔细琢磨了下，可能老生常谈就不太合适

2020-10-07 08:02 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +空安全是我们对 Dart 作出最大的改变。
感觉是一项不兼容的改动，而且如果跟类型系统的改动级别类似的话，可能还是「改变」好一些

2020-10-07 08:03 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +空安全已经成为 [老生常谈][billion]。让我们来看下面这个例子：
P.S. 老生常谈不是形容词噢~

2020-10-07 08:18 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +如果您在运行这个 Dart 程序时并未使用空安全，
空安全目前是个feature，我寻思它是要手动启用或者要一定的条件的，所以这样应该没啥问题 😄

2020-10-07 08:22 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +运行时的出错很恼人，在本身就是为终端用户的使用而设计的 Dart 语言上尤其如此。
SGTM

2020-10-07 08:24 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +但当一个 Flutter 应用在用户的手机上崩溃时，他们绝对不会感到开心。
「但当一个 Flutter 应用在用户的手机上崩溃了，他们的体验就会大打折扣。」

2020-10-07 08:26 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +因为它可以让开发者在开发时，更多时候是在使用 IDE 编译时，通过类型检查发现错误。
因为它通常可以让使用 IDE 的开发者通过类型检查发现错误。

2020-10-07 08:27 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +它包含了对静态类型系统的修改、一系列的修改及新的语言特性，
它包含了对静态类型系统及诸多方面的修改，以及新的语言特性

2020-10-07 08:29 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +    现有的大多数 Dart 代码都是动态正确的，并且不会抛出空引用错误。
我的理解是有一些代码需要在runtime进行检查，但是它们大多数在进行推导或者隐式转换时都能得到一个正常的结果，所以叫「动态正确」

2020-10-07 08:35 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +    （不过，请注意第一条原则：您可以选择在运行时将检查放在任何位置。）
（不过，根据第一条原则，在运行时何时何地进行检查，完全由您自己掌握。）

2020-10-07 08:38 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +    代码的健全性极大程度影响用户对于代码的信心程度。
我的理解是：
代码的健全性极大程度地决定了开发者对于自己的代码是否有自信。

2020-10-07 08:40 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +`null` 并不糟糕，糟糕的是**在您意想不到的地方出现**，最终引发问题。
`null` 并不糟糕，糟糕的是**它在您意想不到的地方出现**，最终引发问题。

2020-10-10 12:48 UTC, Vadaski requested changes
到家了继续 review，Alex 可以先看一部分

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +我们已经将所有的类型设置为**默认不可空**。
我理解这里应该在说 「变量不可空」，所有变量必定管理了非空对象

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +自此，我们修复了所有的空引用错误。
「自此，我们」=> 「这样，我们就」

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +如果我们认为 `null` 根本不重要，那么我们也许已经停下了。
「如果 null 对我们来说没有什么意义的话，那大可不必再研究下去了。」

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +如果我们认为 `null` 根本不重要，那么我们也许已经停下了。
个人语感，供参考

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +此处我们希望 `dairy` 参数只能传入任意字符串，或者一个 `null` 值。
这里「只能传入任意」，和中文通常理解习惯有些相悖，直觉就会很诡异。「这里我们希望 `dairy` 参数不仅能够传任意字符串也允许传 `null` 值。」建议按照实际意义和中文语境来。

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +本质上，这和定义了一个原有类型加 `Null` 的 [组合类型][union]相差无几。
「相差无几」=>「没有什么区别」
hi Team @AlexV525 @chenglu 
这里是我个人翻译习惯的一些建议。我们在翻译的时候应该尽量使用通俗易懂的表达方式，以降低读着的阅读成本。虽然此处「相差无几」，和「没有什么区别」看上去都有些不重要（感觉都行），但是大量的这样的表达，我觉得可能会无形中给读着带来阅读负担。比如一句话可能要反复看几遍才能知道它究竟在说什么，我建议尽量使用平普的表达方式来做。各位觉得怎么样。

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +您会如何处理可空类型的表达式的结果？
这里还是建议分开翻译，易于理解：
「如果一个表达式的值可能为空，那您会如何处理它呢？」

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +因为您在其值为 `null` 的时候调用方法将会失败，所以我们不会允许您这样做。
「如果表达式的值为空，那么我们就必须禁止你调用它的方法以确保不会出错。」仅个人建议，供译者参考

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +这段代码将毫无疑问地在运行时崩溃。
我理解这里应该不是指的运行时，而是指的，「如果我们允许你去运行这样的代码，那么一定会出现崩溃」，这里 String? 是已经开启 null safety，编译都通不过的；）

2020-10-10 12:48 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +我们只会让您访问同时在原有类型及 `Null` 类下同时定义的方法和属性。
「会」=>「允许」
「所以，这里我们只能允许访问在原类型及 `Null` 类下都存在的方法和属性。」

2020-10-11 05:33 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
```dart
final String a = null;
print(a is Null); // true
print(a is String); // false
print(Null is String); // false
```
确实没有在类型判断中表现出子类，我在Discord再确认下

2020-10-11 05:40 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +如果是 `List` 类型，您可以对其调用 `.add()` 或 `[]`。
上文承接了对象~

2020-10-11 05:43 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +当 `null` 传递至其他类型的表达式时，就意味着任何操作都有可能失败。
「所以当 `null` 传递至其他类型的表达式时，任何操作都有可能失败。」

2020-10-11 05:47 UTC, Vadaski requested changes
review 至 523

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +它们是如何与可空类型交互的呢？
这里的 they 感觉是上下文中隐藏的，我在前面好像没有看到明确指定一个东西，这里直接译为 “它们” 有些突兀。
我理解这里可以翻译为 ，那么我们应该如何使用可空类型呢？ 与下文比较贴合

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +我们将所有的可空类型作为基础类型的子类。
可以添加一个 “所以”，与上句解释承接

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +但当你背道而驰，将一个可空类型传递给非空的基础类型，是不安全的。
“背道而驰” 很酷，但不太建议译文中有这样的表达，建议此处可省略，因为后面的信息量足够了。

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +需要 `String` 的代码可能会在您传递的值上调用 `String` 的方法。
建议译为 声明为 “String” 变量可能会调用 “String” 类型所包含的方法。

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +假设您将类型为 `Object` 的值传递给了需要 `String` 的函数，
建议将“值”翻译为“对象”

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +在运行时进行转换可能会抛出异常，但在编译时，Dart 认为这是可行的。
“Dart 认为这是可行的” =>“Dart 允许这样的操作”

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +值得注意的是，过去您可能已经遭受了它的摧残：
“值得注意的是” 听着有些奇怪，这里没有特别的含义，是否可以不译？ 待议。

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +在隐式转换移除后，这就变成了一个编译错误。
nice，我之前被这玩意儿搞的头疼

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +这么看来，可空类型基本宣告毫无作用了。它们不包含任何方法，您也无法抛下它们扬长而去。
"您也无法抛下它们扬长而去" 不太适合技术类文章的表达，还是建议贴合读者阅读习惯。
“但你也不能完全抛弃它们” 如何，待议

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +如果这张有向图的顶部有是一个单一的超类（直接或间接），那么这个类型称为**顶层类型**。
这里 top type 是不是打个括号把原文也提供给读者会比较好？

2020-10-11 05:47 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +取而代之是一个全新的底层类型 `Never`：
有意思

2020-10-11 06:22 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +本质上，这和定义了一个原有类型加 `Null` 的 [组合类型][union]相差无几。
No problem 👍

2020-10-11 06:37 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +这段代码将毫无疑问地在运行时崩溃。
「如果我们允许这样的代码运行，那么它将毫无疑问地崩溃。」

2020-10-11 06:38 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +我们只会让您访问同时在原有类型及 `Null` 类下同时定义的方法和属性。
「会让」=>「允许」

2020-10-11 06:45 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +它们是如何与可空类型交互的呢？
指的是原有类型

2020-10-11 06:46 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +我们将所有的可空类型作为基础类型的子类。
在此次改动中，我们将所有的可空类型作为基础类型的子类。

2020-10-11 06:51 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +假设您将类型为 `Object` 的值传递给了需要 `String` 的函数，
「值」-> 「实例」

2020-10-11 06:53 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +值得注意的是，过去您可能已经遭受了它的摧残：
您可能已经遭受过它的摧残

2020-10-11 06:58 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +这么看来，可空类型基本宣告毫无作用了。它们不包含任何方法，您也无法抛下它们扬长而去。
它们不包含任何方法，但是您又无法摆脱它们。

2020-10-11 07:03 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +如果这张有向图的顶部有是一个单一的超类（直接或间接），那么这个类型称为**顶层类型**。
Top type 根据的是 wikipedia 的引用 https://en.wikipedia.org/wiki/Top_type

2020-10-11 07:33 UTC, Vadaski requested changes
review 至 1296

2020-10-11 07:33 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +在您的程序中，一个智能的准确知晓 `null` 去向的可达性分析，
”智能的准确知晓“ 我觉得保留一半就好了

2020-10-11 07:33 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +在您的程序中，一个智能的准确知晓 `null` 去向的可达性分析，
或者是 “一个准确知晓 `null` 去向的智能可达性分析” 这样？

2020-10-11 07:33 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +## 与可空类型共舞
赞

2020-10-11 07:33 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +然而，如果您曾经在 Dart 中使用过空判断操作符，您可能经历过链式方法调用的恼人操作。
null-aware operators 在之前的翻译中为 ”避空运算符“ 建议保持一致

2020-10-11 07:46 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +    因为它意味着“除了诡异的 `null` 值以外的任何可能的值”。
使用 `Object` 后会使得代码的行为变得非常诡异，因为它意味着能够是“除了 `null` 以外的任何实例”。

2020-10-11 07:47 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +我们将类型世界砍成了非空和可空的两半。
划分为

2020-10-11 07:49 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +也许您写了一个辅助函数，用于简单方便地抛出一个固定的异常：
也许您会写一个辅助函数

2020-10-11 07:52 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +同时我们也通过绝对赋值分析使得**终值**变量更灵活。
这里我觉得需要，因为说的就是终值的初始化，但是可以调整下：
「同时我们也通过绝对赋值分析使得声明为 **final** 的变量更灵活。」

2020-10-11 07:55 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +在您的程序中，一个智能的准确知晓 `null` 去向的可达性分析，
一个可以准确知晓 `null` 去向的可达性分析

2020-10-11 09:14 UTC, Vadaski requested changes
review 完毕，译者辛苦啦

2020-10-11 09:14 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +如果破坏了这些代码，会直接点燃 Dart 的生态系统。
”点燃” => ”摧毁“ ?

2020-10-11 09:14 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +    非空的全局变量和静态字段必须包含构造。
"必须包含构造"=> "被初始化"

2020-10-11 09:16 UTC, AlexV525 commented on src/null-safety/understanding-null-safety/index.md
> +随着空安全的引入，我们将这个角补充上了。
三种

2020-10-12 05:03 UTC, Vadaski commented on src/null-safety/understanding-null-safety/index.md
> +随着空安全的引入，我们将这个角补充上了。
没理解，哈哈哈

2020-10-13 02:50 UTC, chenglu approved these changes

2020-10-13 02:52 UTC, merged