Create dart-run.md
cfug/dart.cn pull request #315
Opened 2021-08-15 10:31 UTC by evle

2021-08-15 12:04 UTC, AlexV525 requested changes
感谢翻译！请先对照以下内容进行自查，调整后我们会继续跟进：
* [翻译质量要求](https://github.com/cfug/flutter.cn/wiki/%E7%BF%BB%E8%AF%91%E6%80%BB%E8%A6%81%E6%B1%82-(Translation-Guide))
* [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/%E6%96%87%E6%A1%A3%E7%BF%BB%E8%AF%91%E6%A0%BC%E5%BC%8F-(Translation-Spec))

2021-08-15 14:35 UTC, evle commented
> 感谢翻译！请先对照以下内容进行自查，调整后我们会继续跟进：
> 
> * [翻译质量要求](https://github.com/cfug/flutter.cn/wiki/%E7%BF%BB%E8%AF%91%E6%80%BB%E8%A6%81%E6%B1%82-(Translation-Guide))
> * [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/%E6%96%87%E6%A1%A3%E7%BF%BB%E8%AF%91%E6%A0%BC%E5%BC%8F-(Translation-Spec))

按照文档翻译格式调整了一下 谢谢

2021-08-15 15:06 UTC, AlexV525 commented on src/tools/dart-run.md
> +description: Command-line tool for running a Dart program.
另起一行写中文描述

2021-08-15 15:17 UTC, evle commented on src/tools/dart-run.md
> +description: Command-line tool for running a Dart program.
已修改

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +`dart run` 命令支持从文件、当前包或者当前包的依赖中运行Dart程序。该命令提供以前在`pub run`和Dart虚拟机工具提供的功能。
```suggestion
`dart run` 命令支持运行文件、当前 package
或者当前 package 的依赖中运行Dart程序。
该命令提供了以前在 `pub run` 和 Dart VM 工具里提供的功能。
```

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +如果想从任意位置运行程序, 可以使用[pub global](/tools/pub/cmd/pub-global) 命令。
注意标点和空格。

```suggestion
如果想从任意位置运行程序，可以使用 [pub global](/tools/pub/cmd/pub-global) 命令。
```

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +下面的例子演示了如何创建并且运行一个Dart程序:
其余位置请同样修正中英文之间的空格，同样需要注意标点。

```suggestion
下面的例子演示了如何创建并且运行一个 Dart 程序：
```

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +## 运行包中的Dart程序
package 不翻译。后同

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +本节中的说明假设你在当前Dart包的根目录执行'dart run'命令。
```suggestion
本节说明的前提是你在 package 的根目录执行 `dart run` 命令。
```

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +你可以运行当前包所依赖的任何包的Dart程序, 只要它在`bin`目录下。运行时请指定依赖的包名和程序名。
一般成句后即可换行，保持工整及可读性。

```suggestion
你可以运行当前 package 所依赖的任何 package 的 Dart 程序, 只要它在 `bin` 目录下。
运行时请指定依赖的包名和程序名。
```

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +当当前目录与包名匹配时(也就是说，你在的目录与pubspec中的`name`属性匹配)，可以省略包名。如果程序名与包名匹配(也就是说，它是main程序)，也可以省略程序名。
```suggestion
当当前的路径与包名匹配时（等同于文件夹名称与 pubspec 中的 `name` 属性相同），
可以省略包名。如果程序名与包名匹配（也就是它是 main 程序），也可以省略程序名。
```

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +[给 `main()` 函数传递参数][args]，只需要在命令行后面添加参数:
```suggestion
若你需要 [给 `main()` 函数传递参数][args]，在命令行后面添加参数即可：
```

2021-08-15 15:19 UTC, AlexV525 commented on src/tools/dart-run.md
> +如果在开发中想尝试实验性功能, 可以通过传入 [experiment flags](/tools/experiment-flags) 参数。
```suggestion
如果在开发中想尝试实验性功能, 可以使用 [实验性功能开关](/tools/experiment-flags)。
```

2021-08-15 16:00 UTC, evle commented on src/tools/dart-run.md
> +## 运行包中的Dart程序
非常感谢修正建议

2021-08-16 03:43 UTC, AlexV525 reviewed
感谢跟进，重新 review 后发现还有一些可以改进的地方~

2021-08-16 03:43 UTC, AlexV525 commented on src/tools/dart-run.md
> +当当前的路径与 package 名匹配时（等同于文件夹名称与 pubspec 中的 `name` 属性相同），
```suggestion
当当前的路径与 package 名匹配时（即文件夹名称与 pubspec 中的 `name` 属性相同），
```

2021-08-16 03:43 UTC, AlexV525 commented on src/tools/dart-run.md
> +`dart run` 是运行 Dart 程序最短的形式，它运行当前 package 的主程序。
```suggestion
`dart run` 是运行 Dart 程序最短的形式，它会运行当前 package 的主程序。
```

2021-08-16 03:43 UTC, AlexV525 commented on src/tools/dart-run.md
> +例如，如果你在 package `foo` 的根目录，通过下面命令则会运行 `bin/foo.dart` 文件：
```suggestion
例如，如果你在 package `foo` 的根目录执行下面命令，实际上会运行 `bin/foo.dart` 文件：
```

2021-08-16 03:43 UTC, AlexV525 commented on src/tools/dart-run.md
> +如果程序名和 package 名不同，需要使用 `:<程序名>` 的形式来运行程序，比如运行当前 package 中的 `bin/baz.dart` 文件:
```suggestion
如果程序名和 package 名不同，需要使用 `:<程序名>` 的形式来运行程序，
比如运行当前 package 中的 `bin/baz.dart` 文件:
```

2021-08-16 03:43 UTC, AlexV525 commented on src/tools/dart-run.md
> +要运行的程序在当前 package，但不在 `bin` 目录时，通过传递相对路径运行（如前面说的）：
```suggestion
要运行在当前 package 但不在 `bin` 目录的程序时，通过传递相对路径运行（如前文所示）：
```

2021-08-16 03:43 UTC, AlexV525 commented on src/tools/dart-run.md
> +在当前 package 中运行 `main` 程序需要添加 package 名，比如要传递参数并运行位于 `foo` package 根目录中的 `bin/foo.dart` 程序：
```suggestion
在当前 package 中运行 `main` 程序需要添加 package 名，
比如要传递参数并运行位于 `foo` package 根目录中的 `bin/foo.dart` 程序：
```

2021-08-16 03:45 UTC, AlexV525 commented
另外，合并建议 suggestions 时，可以在「Files changed」Tab 下，点击「Apply suggestion to batch」将 suggestions 加入批处理，点击「Commit suggestions」一并合并。
![image](https://user-images.githubusercontent.com/15884415/129508803-22a8f603-d78f-48f1-bd77-945bb19a73a6.png)

2021-08-17 07:52 UTC, evle commented
> 另外，合并建议 suggestions 时，可以在「Files changed」Tab 下，点击「Apply suggestion to batch」将 suggestions 加入批处理，点击「Commit suggestions」一并合并。
> ![image](https://user-images.githubusercontent.com/15884415/129508803-22a8f603-d78f-48f1-bd77-945bb19a73a6.png)

感谢建议！

2021-08-17 08:31 UTC, AlexV525 approved these changes
LGTM

2021-08-17 09:47 UTC, AlexV525 commented
Landing on RED since analysis results are nothing related to this PR.

2021-08-17 09:48 UTC, merged