[完成翻译] src/_guides/language/concurrency/index.md
cfug/dart.cn pull request #349
Opened 2021-12-27 15:30 UTC by AlexV525

### 解决的任务 Issue

无关联 issues。

2021-12-28 16:13 UTC, AlexV525 commented
Addressing codes update at https://github.com/dart-lang/site-www/pull/3739.

2022-01-10 12:31 UTC, Nayuta403 approved these changes
❤️ ❤️

2022-01-10 12:31 UTC, Nayuta403 commented on src/_guides/language/concurrency/index.md
> +在需要进行交换的场景里，isolate 会使用消息通信机制。
```suggestion
在需要进行通信的场景里，isolate 会使用消息机制。
```

2022-01-10 12:31 UTC, Nayuta403 commented on src/_guides/language/concurrency/index.md
> +你可以直接跳到 [isolate 部分][isolates section] 进行阅读。
```suggestion
可以直接跳到 [isolate 部分][isolates section] 进行阅读。
```

2022-01-10 12:31 UTC, Nayuta403 commented on src/_guides/language/concurrency/index.md
> +这时应用可能会产生卡顿，所有的动画都无法顺畅播放。
```suggestion
这时应用可能会产生卡顿，所有的动画都无法流畅播放。
```
顺畅感觉怪怪的

2022-01-10 16:36 UTC, Vadaski commented
赞

2022-01-10 16:52 UTC, chenglu commented
审核完发一篇公众号文章吧~

2022-01-10 16:57 UTC, Vadaski requested changes
还有一些小问题需要A少再康康

2022-01-10 16:57 UTC, Vadaski commented on src/_guides/language/concurrency/index.md
> +在应用中，所有的 Dart 代码都运行在一个 **isolate** 内。
an 可不译，强行翻译感觉就不对了

2022-01-10 16:57 UTC, Vadaski commented on src/_guides/language/concurrency/index.md
> +在应用中，所有的 Dart 代码都运行在一个 **isolate** 内。
去掉[一个]

2022-01-10 16:57 UTC, Vadaski commented on src/_guides/language/concurrency/index.md
>    Dart web apps can use [web workers][] for similar functionality.
这句翻译漏掉了～

2022-01-10 16:57 UTC, Vadaski commented on src/_guides/language/concurrency/index.md
> +Isolate 与线程和进程近似，但是每个 isolate 都拥有独立的内存，以及运行时间循环的独立线程。
时间循环 ＝> 事件循环

2022-01-10 16:57 UTC, Vadaski commented on src/_guides/language/concurrency/index.md
> +下图展示了一种常用场景，你可以生成一个 isolate，它将执行耗时计算，结束后退出。
执行耗时计算任务，供参考

2022-01-13 01:46 UTC, AlexV525 commented on src/_guides/language/concurrency/index.md
> +Dart 通过 async-await、isolate 和 `Future` 及 `Stream` 两种类型概念支持了并发代码编程。
我在这儿用了 **及**，也是想表达它俩是一块儿的

2022-01-13 02:57 UTC, Nayuta403 commented on src/_guides/language/concurrency/index.md
> +Dart 通过 async-await、isolate 和 `Future` 及 `Stream` 两种类型概念支持了并发代码编程。
额，上面的译文我个人读下来感觉是说，这三种平级的概念都能支持并发编程（虽然我在想 async-await 也是 Future ）。
但最后一种他用的是

> classes such as `Future` and `Stream`.

我觉得他想说应该是有一些类，例如，Future 和 Stream，但是不仅只有这两种，相关的比如 FutureOr 。

>   `Future` 及 `Stream` 两种类型概念支持了并发代码编程。

这个读起来会不会认为这一类只有 `Future` 及 `Stream` 🤔。

2022-01-13 03:20 UTC, AlexV525 commented on src/_guides/language/concurrency/index.md
> +Dart 通过 async-await、isolate 和 `Future` 及 `Stream` 两种类型概念支持了并发代码编程。
调整：Dart 通过 async-await、isolate 以及一些异步类型概念（例如 `Future` 和 `Stream`）支持了并发代码编程。

2022-01-14 08:11 UTC, Nayuta403 approved these changes
LGTM

2022-01-14 08:13 UTC, merged