[内容修订] src/_guides/language/effective-dart/documentation.md
cfug/dart.cn pull request #410
Opened 2022-11-22 16:52 UTC by YogiLiu

### 解决的 Issues
Fix #409 

### 更新内容描述

优化译文，并补充部分翻译。

2022-11-30 04:28 UTC, MeandNi requested changes
a nit.

2022-11-30 04:28 UTC, MeandNi commented on src/_guides/language/effective-dart/documentation.md
> +### **要** 使用普通的语句来描述参数、返回值以及异常信息。
```suggestion
### **要** 使用平白简单的语句来描述参数、返回值以及异常信息。
```

2022-12-01 09:13 UTC, AlexV525 commented on src/_guides/language/effective-dart/documentation.md
> +简明、扼要的注释只需花费几秒钟的时间去写，但可以让每个这样的人节约几个小时。
```suggestion
写下简明扼要的注释只需要几秒钟，但可以让看这段代码的每个人节约几个小时。
```

2022-12-01 09:13 UTC, AlexV525 commented on src/_guides/language/effective-dart/documentation.md
> +Dart 的惯例是将其整合到方法的描述中，并使用方括号强调参数。
```suggestion
Dart 的惯例是将其整合到方法的描述中，使用方括号高亮并标记参数。
```

2022-12-03 05:38 UTC, AlexV525 approved these changes

2022-12-03 05:38 UTC, merged