[完成翻译] src/language/variables
cfug/dart.cn pull request #443
Opened 2023-11-28 06:24 UTC by mobeicanyue

### 解决的任务 Issue
Resolve #442

完成了{src/language/variables.md}翻译， ~~由于没找到具体的要求（如换行、链接、注释等），就参考别的md格式排版了，~~ 如果有需要改进的地方还请指出。

2023-11-28 06:32 UTC, AmosHuKe commented
@mobeicanyue 
可以参考一下：
- [文档翻译格式 (Translation Spec)](https://github.com/cfug/flutter.cn/wiki/%E6%96%87%E6%A1%A3%E7%BF%BB%E8%AF%91%E6%A0%BC%E5%BC%8F-(Translation-Spec))
- [翻译总要求 (Translation guide)](https://github.com/cfug/flutter.cn/wiki/%E7%BF%BB%E8%AF%91%E6%80%BB%E8%A6%81%E6%B1%82-(Translation-Guide))
- [中文文案排版指南 (Chinese Typography Guide)](https://github.com/cfug/flutter.cn/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%88%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97-(Chinese-Typography-Guide))

2023-11-29 07:04 UTC, AlexV525 commented on src/language/variables.md
> +你可以定义使用 [type checks and casts][](`is` 和 `as`)、[collection `if`][] 和 [spread operators][](`...` 和 `...?`)的常量：
```suggestion
你可以在定义常量时使用 [类型检查和转换][type checks and casts]（`is` 和 `as`）、
[集合中的 `if`][collection `if`] 和
[展开操作符][spread operators]（`...` 和 `...?`）：
```

2023-11-29 07:04 UTC, AlexV525 commented on src/language/variables.md
>  For more information on using `const` to create constant values, see
note 没有翻译

2023-11-29 07:04 UTC, AlexV525 commented on src/language/variables.md
> +`const` 关键字不仅用于声明常量变量。你还可以使用它来创建常量 _值(values)_，以及声明 _创建(create)_ 常量值的构造函数。任何变量都可以拥有常量值。
使用 `**` 而不是 `_`

2023-11-29 07:04 UTC, AlexV525 commented on src/language/variables.md
> +你可以省略 `const`  声明中的初始化表达式，就像上面的 `baz` 一样。详细信息，请看[DON'T use const redundantly][]。
链接没有翻译

2023-11-29 07:04 UTC, AlexV525 commented on src/language/variables.md
> +如果你永不打算更改变量，可以使用 `final` 或 `const` ，而不是 `var` 或作为类型附加。一个final变量只能设置一次；const变量是编译时常量。（const变量隐式为final。）
英文没有空格

2023-11-29 13:42 UTC, AmosHuKe commented on src/language/variables.md
>  For more information on using `const` to create constant values, see
@mobeicanyue 上面的 note

按下面这样的格式（注意原文首行换行）

```md
{{site.alert.note}}

  Although a `final` object cannot be modified,
  its fields can be changed. 
  In comparison, a `const` object and its fields
  cannot be changed: they're _immutable_.

  翻译内容............

{{site.alert.end}}
```

2023-12-02 04:51 UTC, AlexV525 requested changes

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +  该页面遵循 [风格指南推荐][style guide recommendation](/effective-dart/design#types) ，建议在局部变量中使用 `var`，而不是类型注解。
```suggestion
  文章遵循 [代码风格指南][style guide recommendation](/effective-dart/design#types) ，
  使用的是 `var` 声明局部变量，而不是使用准确的类型。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +空安全防止因意外访问被设置为 `null` 的变量而导致的错误。该错误被称为空解引用错误。访问一个求值为 `null` 的表达式的属性或调用方法时，会发生空解引用错误。此规则的一个例外是当 `null` 支持像 `toString()` 或 `hashCode` 这样的属性或方法。使用空安全，Dart 编译器可以在编译时检测到这些潜在的错误。
```suggestion
空安全能够防止意外访问 `null` 的变量而导致的错误。
这样的错误也被称为空解引用错误。
访问一个求值为 `null` 的表达式的属性或调用方法时，会发生空解引用错误。
但是对于 `toString()` 方法和 `hashCode` 属性，空安全会体现出例外情况。
Dart 编译器可以在空安全的基础上在编译期检测到这些潜在的错误。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +有关使用 `const` 创建常量值的更多信息，请参见 [Lists][Lists]、[Maps][Maps] 和 [Classes][Classes]。
```suggestion
有关使用 `const` 创建常量值的更多信息，请参见
[Lists][]、[Maps][] 和 [Classes][]。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +  虽然 `final` 对象不能被修改，但它的字段可以被更改。相比之下，`const` 对象及其字段不能被更改：它们是 **不可变的**。
```suggestion
  虽然 `final` 对象不能被修改，但它的字段可能可以被更改。
  相比之下，`const` 对象及其字段不能被更改：它们是 **不可变的**。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +你可以更改非final、非const变量的值，即使它以前有 `const` 的值：
这句读起来没有表达出该有的意思

```suggestion
如果变量没有以 `final` 或者 `const` 修饰，
即使它以前有的值是一个 `const` 修饰的值，
你也可以修改这个变量：
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +你可以省略 `const`  声明中的初始化表达式，就像上面的 `baz` 一样。详细信息，请看 [不要重复使用常量][DON'T use const redundantly]。
```suggestion
你可以省略以 `const` 声明中的值的 `const` 修饰，就像上面的 `baz` 一样。
更多详细信息请参考 [不要重复使用常量][DON'T use const redundantly]。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +`const` 关键字不仅用于声明常量变量。你还可以使用它来创建常量 **值(values)**，以及声明 **创建(create)** 常量值的构造函数。任何变量都可以拥有常量值。
```suggestion
`const` 关键字不仅仅可用于声明常量，
你还可以使用它来创建常量 **值(values)**，以及声明 **创建(create)** 常量值的构造函数。
任何变量都可以拥有常量值。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +对于希望成为 **编译时常量** 的变量，请使用 `const`。如果 const 变量位于类级别，请将其标记为 `static const`。在声明变量的位置，将其值设置为编译时常量，比如数字或字符串字面量，`const` 变量，或在常量数字上进行的算术运算的结果：
没有换行，没有用对标点

```suggestion
请使用 `const` 修饰 **编译时常量** 的变量。
如果 const 变量位于类级别，请将其标记为 `static const`（静态常量）。
在声明变量的位置，将其值设置为编译时常量，
比如数字、字符串、`const` 常量或在常量数字上进行的算术运算的结果：
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +如果你永不打算更改变量，可以使用 `final` 或 `const` ，而不是 `var` 或作为类型附加。一个 final 变量只能设置一次；const 变量是编译时常量。（const 变量隐式为 final。）
```suggestion
如果你打算不再更改一个变量，可以使用 `final` 或 `const` 声明它 ，而不是 `var` 或作为类型附加。
一个 final 变量只能设置一次，const 变量是编译时常量。
（const 常量隐式包含了 final。）
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +## Final和const
Final 对于中文中的英文是没有意义的，所以它是作为普通释义来解释的。这里可以写上释义加原文来表述

```suggestion
## 终值 (final) 和常量 (const)
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +在下面的例子中，如果从未使用 `temperature` 变量，则永远不会调用高开销的 `readThermometer()` 函数：
```suggestion
在下面的例子中，如果 `temperature` 变量从未被使用，
则 `readThermometer()` 这个开销较大的函数也永远不会被调用：
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +  (Dart 认为)可能不需要该变量，并且初始化它开销很高。
```suggestion
  （Dart 推断）可能不需要该变量，并且初始化它的开销很高。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +当一个 `late` 修饰的变量在声明时就指定了初始化方法，那么初始化程序会在第一次使用变量时运行。这种延迟初始化在以下情况很方便：
```suggestion
当一个 `late` 修饰的变量在声明时就指定了初始化方法，
那么内容会在第一次使用变量时运行初始化。
这种延迟初始化在以下情况很方便：
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +如果你确定变量在使用之前已设置，但 Dart 判断失误的话，则可以通过将变量标记为 `late` 来解决这个问题：
```suggestion
如果你确定变量在使用之前已设置，但 Dart 推断错误的话，
可以将变量标记为 `late` 来解决这个问题：
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +你不必在声明变量时初始化变量，但在使用之前需要为其赋值。例如，以下代码是合法的，因为 Dart 可以检测到 `lineCount` 在传递给 `print()` 时是非空的：
```suggestion
你不必在声明变量时初始化变量，但在使用之前需要为其赋值。
例如以下代码是合法的，因为 Dart 可以检测到 `lineCount` 在传递给 `print()` 时是非空的：
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +此检查允许你在部署应用程序 _之前(before)_ 修复这些错误。
没有用 **

```suggestion
此检查允许你在部署应用程序 **之前** 修复这些错误。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +   你不能在可空类型的表达式上访问属性或调用方法。同样的例外情况适用于 `null` 支持的属性或方法，例如 `hashCode` 或 `toString()` 。
```suggestion
   你不能在可空类型的表达式上访问属性或调用方法。
   同样的例外情况适用于 `null` 支持的属性或方法，例如 `hashCode` 或 `toString()` 。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +    你必须在使用变量之前对其进行初始化。可空变量默认为 `null` ，所以它们是默认初始化的。Dart 不会为非可空类型设置初始值，而是强制你设置初始值。Dart 不允许你观察未初始化的变量。这可以防止你在接收者类型可以为 `null` 但 `null` 不支持所使用的方法或属性 的情况下访问属性或调用方法。
多余的空格

```suggestion
    你必须在使用变量之前对其进行初始化。
    可空变量是默认初始化为 `null` 的。
    Dart 不会为非可空类型设置初始值，它强制要求你设置初始值。
    Dart 不允许你观察未初始化的变量。
    这可以防止你在接收者类型可以为 `null` 但 `null`
    不支持的相关方法或属性的情况下使用它。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +    当你为变量、参数或另一个相关组件指定类型时，可以控制该类型是否允许 `null` 。要启用可空性，你可以在类型声明的末尾添加 `?` 。
```suggestion
    当你为变量、参数或另一个相关组件指定类型时，可以控制该类型是否允许 `null` 。
    要让一个变量可以为空，你可以在类型声明的末尾添加 `?` 。
```

2023-12-02 04:51 UTC, AlexV525 commented on src/language/variables.md
> +例如，假设你想要查找 `int` 变量 `i` 的绝对值。如果 `i` 是 `null` ，调用 `i.abs()` 会导致空解引用错误。在其他语言中，尝试这样做可能会导致运行时错误，但是 Dart 的编译器禁止这些操作。因此，Dart 应用程序不会引发运行时错误。
```suggestion
例如，假设你想要查找 `int` 变量 `i` 的绝对值。
如果 `i` 是 `null` ，调用 `i.abs()` 会导致空解引用错误。
在其他语言中，尝试这样做可能会导致运行时错误，但是 Dart 的编译器禁止这些操作。
所以 Dart 应用程序不会引发运行时错误。
```

2023-12-02 04:59 UTC, AlexV525 commented
在 Files 标签中可以一次性应用全部 suggestion。

2023-12-02 07:20 UTC, AlexV525 commented
还有 15 条没有处理。

2023-12-02 07:35 UTC, AmosHuKe commented on src/language/variables.md
> +  文章遵循 [代码风格指南][style guide recommendation](/effective-dart/design#types) ，
```suggestion
  文章遵循 [代码风格指南](/effective-dart/design#types) ，
```

2023-12-02 07:43 UTC, AlexV525 commented on src/language/variables.md
> +下面是一个创建并初始化变量的例子：
```suggestion
下面是创建并初始化变量的例子：
```

2023-12-02 07:44 UTC, AlexV525 commented
![image](https://github.com/cfug/dart.cn/assets/15884415/bf8bb6c5-b04a-485c-9cbc-90e32a4f6116)

2023-12-04 04:22 UTC, AlexV525 approved these changes
感谢参与翻译工作！

2023-12-04 04:22 UTC, merged